export const MessageCode = {
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  MISSING_FIELDS: "MISSING_FIELDS",
  SERVER_CONFIG: "SERVER_CONFIG",
  NETWORK_ERROR: "NETWORK_ERROR",
  INVALID_DISPLAY_NAME: "INVALID_DISPLAY_NAME",
  UNAUTHORIZED: "UNAUTHORIZED",
  SERVER_ERROR: "SERVER_ERROR",
  UNKNOWN_GAME: "UNKNOWN_GAME",
  UNAVAILABLE_GAME: "UNAVAILABLE_GAME",
  INVALID_GAME_SETTINGS: "INVALID_GAME_SETTINGS",
  INVALID_ROUND: "INVALID_ROUND",
  NO_ACTIVE_SESSION: "NO_ACTIVE_SESSION",
  SESSION_EXISTS: "SESSION_EXISTS",
  INVALID_SCORE: "INVALID_SCORE",
  GAME_COMPLETED: "GAME_COMPLETED",
  NO_ROUNDS_TO_UNDO: "NO_ROUNDS_TO_UNDO",
  INVALID_DART_OUTCOME: "INVALID_DART_OUTCOME",
  NO_DARTS_TO_UNDO: "NO_DARTS_TO_UNDO",
} as const;

export type MessageCode = (typeof MessageCode)[keyof typeof MessageCode];

export const errorMessages: Record<MessageCode, string> = {
  [MessageCode.INVALID_CREDENTIALS]: "Invalid email or password",
  [MessageCode.MISSING_FIELDS]: "Email and password are required",
  [MessageCode.SERVER_CONFIG]: "Server configuration error",
  [MessageCode.NETWORK_ERROR]: "Unable to connect. Please try again.",
  [MessageCode.INVALID_DISPLAY_NAME]: "Display name must be 2–20 characters",
  [MessageCode.UNAUTHORIZED]: "You must be logged in",
  [MessageCode.SERVER_ERROR]: "Something went wrong. Please try again.",
  [MessageCode.UNKNOWN_GAME]: "That game does not exist.",
  [MessageCode.UNAVAILABLE_GAME]: "That game is not available yet.",
  [MessageCode.INVALID_GAME_SETTINGS]: "Invalid game settings.",
  [MessageCode.INVALID_ROUND]: "Invalid round data.",
  [MessageCode.NO_ACTIVE_SESSION]: "No active session found.",
  [MessageCode.SESSION_EXISTS]: "A session already exists for this game.",
  [MessageCode.INVALID_SCORE]: "Visit score must be 0–180.",
  [MessageCode.GAME_COMPLETED]: "Game is already completed.",
  [MessageCode.NO_ROUNDS_TO_UNDO]: "No rounds to undo.",
  [MessageCode.INVALID_DART_OUTCOME]: "Invalid dart outcome for the current target.",
  [MessageCode.NO_DARTS_TO_UNDO]: "No darts to undo.",
};
